# Generated by Django 5.2.8 on 2025-11-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='links',
            new_name='address',
        ),
    ]
